### ISSUE TITLE
Re-enable Greenkeeper

### ISSUE THREAD

**Issue by ChristianMurphy** [remarkjs/grunt-remark#35]
It looks like during the repository transfer: Travis CI, AppVeyor, and David DM transferred with no issues.
However it looks like [GreenKeeper](https://greenkeeper.io) did not transfer.

Would it be possible to get [GreenKeeper](https://greenkeeper.io), or one of the equivalent tools: e.g. [Renovate](https://renovateapp.com) enabled?

Thanks :bow:

**Comment by wooorm** [comment]
Heya!

I used greenkeeper a bit for all repo’s, but I feel that it creates too many PRs, so I turned it off again.
Particularly, I don’t like PRs for dev-dependencies: it just creates too much noise on 300 repo’s, and they aren’t that important. If greenkeeper would support just checking dependencies, I’m all 👍.

What do you think?

**Comment by ChristianMurphy** [comment]
I agree GreenKeeper can be noisy.
The idea of automating dependency management is still sound.

I've been moving my repos to renovate because they have better noise reduction options. https://renovateapp.com/docs/deep-dives/noise-reduction
Renovate also allows independently configuring `dependencies`, `devDependencies`, and `peerDependencies`. https://renovateapp.com/docs/configuration-reference/configuration-options
And allows for config to be shared (e.g. `unified-renovate-config`) https://renovateapp.com/docs/configuration-reference/config-presets

No tool is perfect, renovate has its flaws as well.
But competition between tools is good, and right now renovate seems to better handle the noise reduction use cases.

**Comment by ChristianMurphy** [comment]
> I don’t like PRs for dev-dependencies: it just creates too much noise on 300 repo’s, and they aren’t that important.

Agreed they create noise and usually aren't important.
Maybe having a schedule of once a week or once a month devDependency updates could make it more manageable?

**Comment by wooorm** [comment]
Sorry for the wait! Feel free to add either greenkeeper or renovate here, and weekly sounds good to me! Anything you need from me to try this out?

**Comment by ChristianMurphy** [comment]
> Feel free to add either greenkeeper or renovate here, and weekly sounds good to me! 

Cool sounds good!

> Anything you need from me to try this out?

GreenKeeper/Renovate require an organization admin to enable them.
Either an existing admin would need to switch this on, or I'd need to become an admin.

**Comment by wooorm** [comment]
Done! Don’t remove repo’s 😉

**Comment by ChristianMurphy** [comment]
Thanks @wooorm!
Setting up renovate, now, will have a config set to do weekly updates put together shortly.

*If it works out okay*, renovate also supports [shareable configs](https://renovateapp.com/docs/configuration-reference/config-presets), something like `unified-renovate-config` could be created, and be shared across the unified ecosystem.

**Comment by wooorm** [comment]
Sweet! 🎉
Let’s try it out for a few weeks to see what it comes up with, and after that talk about this again?

**Comment by ChristianMurphy** [comment]
Configuration in progress at https://github.com/remarkjs/grunt-remark/pull/36

**Comment by rarkins** [comment]
Hi, I'm the author of Renovate. Ping me any time you have questions or suggestions. My goal is that the bot is configurable to the point it suits anyone's preferences in terms of noise. If it's failing to do that and you have ideas, I'm all ears.
